name: Build Tweak
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Unzip source
        run: |
          unzip -o BonfireCheat_src.zip
          if [ -d "cheat_bonfire2" ]; then
            cp -r cheat_bonfire2/* .
          fi

      - name: Setup Theos
        uses: Randomblock1/theos-action@v1

      - name: Fix Code and Build
        run: |
          # Sửa trực tiếp lỗi ép kiểu void pointer sang function pointer trong file Tweak.xm
          sed -i 's/\*(void\*\*)m/(void (\*)(Il2CppObject \*, void \*))\*(void\*\*)m/g' Tweak.xm

          cat << 'EOF' > Makefile
          TARGET := iphone:clang:latest:14.0
          ARCHS = arm64

          include $(THEOS)/makefiles/common.mk

          TWEAK_NAME = BonfireCheat
          BonfireCheat_FILES = Tweak.xm
          BonfireCheat_FRAMEWORKS = UIKit Foundation
          BonfireCheat_LIBRARIES = substrate
          BonfireCheat_CCFLAGS = -Wno-error -w
          BonfireCheat_CXXFLAGS = -Wno-error -w

          include $(THEOS)/makefiles/tweak.mk
          EOF

          make FINALPACKAGE=1
          mkdir -p output
          find .theos/obj -name "*.dylib" -exec cp {} output/ \;

      - name: Upload Dylib
        uses: actions/upload-artifact@v4
        with:
          name: BonfireCheat-dylib
          path: output/
